name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.16]

    steps:
      - run: git config --global url."https://".insteadOf git://
      - run: git config --global url."https://github.com/".insteadOf git@github.com
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: /usr/local/share/.config/yarn/global
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Compile Solidity contracts
        run: yarn compile
      - run: yarn test
        env:
          TEST_URI: ${{ secrets.TEST_URI }}
          CI: true
